language: rust

jobs:
  include:
  - rust: 1.17.0
    script: cargo test --all-features

  - rust: stable
    script: cargo test --all-features --all

  - rust: beta
    script: cargo test --all-features --all

  - rust: nightly
    script: cargo test --all-features --all

  - rust: nightly
    env: TARGET=WASM32
    install: rustup target add wasm32-unknown-unknown
    script: cargo build --all --target=wasm32-unknown-unknown
